first_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('register.urls')),
    path('api/v1/', include(('mymovieapi.urls', 'mymovieapi'), namespace='mymovieapi')),
    # path('api/v1/', include(('main.urls', 'main'), namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page),
    path('home', views.index),
    path('movies/', views.MovieList.as_view(), name='MovieList'),
    path('movies/create/', views.CreateMovie.as_view(), name='CreateMovie'),
    path('movies/create/actor', views.CreateActor.as_view(), name='CreateActor'),
    path('movies/top/', views.TopMovies.as_view(), name='TopMovies'),
    path('movies/top/<int:pk>', views.TopMovies.as_view(), name='TopIntMovies'),
    path('movies/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail'),
    path('movies/<int:movie_id>/vote', views.CreateVote.as_view(), name='CreateVote'),
    path('movies/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movies/<int:movie_id>/picture/upload', views.MoviePictureUpload.as_view(), name='MoviePictureUpload'),
]

main/models.py
from uuid import uuid4
from django.conf import settings
from django.db import models
from django.db.models.aggregates import Sum
from django.utils import timezone


class PersonManager(models.Manager):
    def all_with_prefetch_films(self):
        qs = self.get_queryset()
        return qs.prefetch_related('actors')


class Person(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField(default=timezone.now)
    died = models.DateField(null=True, blank=True)
    objects = PersonManager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Person'
        verbose_name_plural = 'Persons'

    def __str__(self):
        return self.name


def movie_dir_path_uuid(instance, filename):
    return "{}/{}.{}".format(instance.movie_id, uuid4(), filename.split('.')[-1])


class MoviePicture(models.Model):
    pict = models.ImageField(upload_to=movie_dir_path_uuid)
    upload_time = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_picture', on_delete=models.CASCADE)


class MovieManager(models.Manager):
    def all_persons(self):
        qs = self.get_queryset()
        qs = qs.prefetch_related('actor')
        return qs

    def all_persons_and_score(self):
        qs = self.all_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote__sum=Sum('vote__value'))
        qs = qs.exclude(vote__sum=None)
        qs = qs.order_by('-vote__sum')
        qs = qs[:limit]
        return qs


class Movie(models.Model):
    WITHOUT_RATING = 0
    RATED_WORLD = 1
    RATED_18Y = 2
    RATED_L = 3
    STATUS_RATING = ((WITHOUT_RATING, 'WR - Without rating'),
                     (RATED_WORLD, 'RW - World rated'),
                     (RATED_18Y, 'R18 - 18+ rated'),
                     (RATED_L, 'RL - Limit rated'))
    title = models.CharField('Название фильма', max_length=100)
    preview = models.TextField('Описание фильма', max_length=5000)
    year = models.PositiveIntegerField('Год выпуска', default=1998)
    runtime = models.PositiveIntegerField('Длительность', default=10)
    genre = models.CharField('Жанр фильма', null=True, max_length=100, db_index=True)
    rating = models.IntegerField('Рейтинг фильма', choices=STATUS_RATING, default=WITHOUT_RATING)
    actor = models.ForeignKey(to='Person', null=True, related_name='actors', on_delete=models.SET_NULL, blank=True) # director ... rel_n = directed
    objects = MovieManager()

    class Meta:
        ordering = ('year', 'title')
        verbose_name = 'Film'
        verbose_name_plural = 'Films'

    def __str__(self):
        return "{} ({})".format(self.title, self.year)

    @staticmethod
    def get(pk=None):
        from rest_framework.exceptions import ValidationError
        try:
            qs = Movie.objects.get(pk=pk)
        except Movie.DoesNotExist as ex:
            raise ValidationError(ex)
        return qs


class Roles(models.Model):
    title = models.CharField(max_length=100)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.title)

    class Meta:
        unique_together = ('movie', 'person', 'title')
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'


class VoteManager(models.Manager):
    def get_vote_or_blank(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)


class Vote(models.Model):
    like = 1
    dislike = -1
    value_choice = ((like, '+'), (dislike, '-'))
    # value = models.BigAutoField(choices=value_choice, primary_key=True)   #for old version django 2+, chg migrations
    value = models.SmallAutoField(choices=value_choice, primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_vote', on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    vote_on = models.DateTimeField(auto_now=True)
    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Vote, Movie, MoviePicture, Person
from django.forms import ModelForm, TextInput, DateInput


class VoteForm(ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True, )
    movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True, )
    value = forms.ChoiceField(label='Vote', widget=forms.RadioSelect, choices=Vote.value_choice)

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie')


class MoviePictureForm(ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True, )
    movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True, )

    class Meta:
        model = MoviePicture
        fields = ('pict', 'user', 'movie')


class ActorForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'
        widgets = {'name': TextInput(attrs={'class': 'form-input', 'placeholder': 'Имя'}),
                   'birthday': DateInput(format='%d-%m-%Y', attrs={'class': 'form-control',
                                                                   'placeholder': 'Дата рождения (ГГГГ-ММ-ДД)'}),
                   'died': DateInput(format='%d-%m-%Y', attrs={'class': 'form-control',
                                                               'placeholder': 'Дата смерти (ГГГГ-ММ-ДД)'})}


class MoviesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['actor'].empty_label = 'Актер не выбран'

    class Meta:
        model = Movie
        actor = forms.ModelChoiceField(queryset=Person.objects.all_with_prefetch_films(), to_field_name='actor')
        fields = ['title', 'genre', 'year', 'preview', 'actor']
        widgets = {'title': TextInput(attrs={'class': 'form-input', 'placeholder': 'Название фильма'}),
                   'genre': TextInput(attrs={'class': 'form-input', 'placeholder': 'Жанр'}),
                   'preview': forms.Textarea(attrs={'cols': 50, 'rows': 10, 'placeholder': 'Описание фильма'}),
                   'year': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Год выпуска'})}

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .forms import VoteForm, MoviePictureForm, MoviesForm, ActorForm
from .models import Movie, Vote, Person


def index(request):
    return render(request, 'main/index.html')


class CreateMovie(View):
    def get(self, request):
        form = MoviesForm()
        return render(request, 'main/add_new_movie.html', context={'form': form})

    def post(self, request):
        bound_form = MoviesForm(request.POST)
        if bound_form.is_valid():
            bound_form.save()
            return redirect('MovieList')
        return render(request, 'main/add_new_movie.html', context={'form': bound_form})


class CreateActor(View):
    def get(self, request):
        form = ActorForm()
        return render(request, 'main/add_new_actor.html', context={'form': form})

    def post(self, request):
        bound_form = ActorForm(request.POST)
        if bound_form.is_valid():
            bound_form.save()
            return redirect('CreateMovie')
        return render(request, 'main/add_new_actor.html', context={'form': bound_form})


def main_page(request):
    return render(request, 'main/main_page.html')


class MovieList(ListView):
    template_name = 'main/movies_list.html'
    model = Movie
    # paginate_by = 10


class TopMovies(ListView):
    template_name = 'main/top10movies.html'
    queryset = Movie.objects.top_movies(limit=10)

    def get_queryset(self):
        limit = 10
        qs = Movie.objects.top_movies(limit=limit)
        return qs


class MovieDetail(DetailView):
    queryset = Movie.objects.all_persons_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['picture_form'] = self.movie_picture_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_blank(movie=self.object, user=self.request.user)
            if vote.pk:
                vote_url_form = reverse('UpdateVote', kwargs={'movie_id': vote.movie.id, 'pk': vote.pk})
            else:
                vote_url_form = reverse('CreateVote', kwargs={'movie_id': self.object.id})
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_url_form'] = vote_url_form
        return ctx

    def movie_picture_form(self):
        if self.request.user.is_authenticated:
            return MoviePictureForm()
        return None


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_films()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('MovieDetail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied('user not found' 'log in')
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('MovieDetail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class MoviePictureUpload(CreateView):
    form_class = MoviePictureForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('MovieDetail', kwargs={'pk': movie_id})
        return movie_detail_url

main/templates/main/add_new_actor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add new actor</title>
</head>
<body>
    <h1>Add new actor:</h1>
    <form class="" action="{% url 'CreateActor' %}" method="post">
        <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
                {{ field.errors }}
            {% endif %}
        {{ field }}<br><br>
        {% endfor %}
        <span>{{ error }}</span><br><br>
        <button class="btn btn-success" type="submit">Add new actor</button><br><br>
        <hr>
    </form>
</body>
</html>

main/templates/main/add_new_movie.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Add new movie</title>
</head>
<body>
    <h1>Add new movie:</h1>
    <form class="" action="{% url 'CreateMovie' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
                {{ field.errors }}
            {% endif %}
        {{ field }}<br><br>
        {% endfor %}
        <span>{{ error }}</span><br>
        <h1><a href="{% url 'CreateActor' %}">При отсутствии актера - добавьте нового</a></h1>
        <button class="btn btn-success" type="submit">Add new movie</button><br><br>
        <hr>
    </form>
</body>
</html>

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Hello</title>
</head>
<body>
    <h1>Hello world!!!</h1>
</body>
</html>

main/templates/main/main_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Main</title>
</head>
<body>
    <h1>Главная страница</h1>
</body>
</html>

main/templates/main/movie_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Movie Detail</title>
</head>
<body>
    <h1>{{ object }}</h1>
    <h2>Genre - {{ object.genre }}</h2>
    <ul>{% for pic in object.moviepicture_set.all %}
    <li style="list-style: none;"><img src="{{ pic.pict.url }}"></li>
    </ul>
        {% endfor %}
    <h2>Preview: </h2>
    <p>{{ object.preview }}</p>
    <h2>Main actor:</h2>
    <p>{{ object.actor }}</p>
    <hr>
    {% if vote_form %}
    <form action="{{ vote_url_form }}" method="post">
        {% csrf_token %}
        {{ vote_form.as_p }}
        <button class="btn btn-primary" type="submit">
            Submit
        </button>
    </form>
    {% else %}
    <p>Log in to vote</p>
    {% endif %}
    {% if picture_form %}
    <h3>New Picture</h3>
    <form action="{% url 'MoviePictureUpload' movie_id=object.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ picture_form.as_p }}
        <p>
            <button class="btn btn-primary">
                Add...
            </button>
        </p>
    </form>
    {% endif %}
</body>
</html>

main/templates/main/movies_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Movies</title>
</head>
<body>

    <h1>Movies:</h1>
    <hr>
    <ul style="list-style: none;">
    {% for movie in object_list %}
        <li>
            <a href="{% url 'MovieDetail' pk=movie.id %}">
                <h3>{{ movie }}</h3>
            </a>
        </li>
    {% endfor %}
    </ul>
</body>
</html>

main/templates/main/person_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Person</title>
</head>
<body>
    <h1>{{ object }}</h1>
    <h2>Actor</h2>
</body>
</html>

main/templates/main/top10movies.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Top 10</title>
</head>
<body>
    <h1>TOP 10:</h1>
    <hr>
    <ul style="list-style: none;">
    {% for movie in object_list %}
        <li>
            <a href="{% url 'MovieDetail' pk=movie.id %}">
                <h3>{{ movie }}</h3>
            </a>
        </li>
    {% endfor %}
</body>
</html>